"""MOD-RECO-017 Popularity Scorer constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-017"
PHASE_NAME = "popularity_scored"
SURFACE_ERROR_CODE = "GRS-REC-012"

POPULARITY_FORMULA_RATING_REVIEW_COUNT_WEIGHTED = "rating_review_count_weighted"
POPULARITY_FORMULA_DEFAULT = POPULARITY_FORMULA_RATING_REVIEW_COUNT_WEIGHTED

DEFAULT_W_RATING = 0.60
DEFAULT_W_REVIEW_COUNT = 0.40

RATING_SCALE = 5.0
NEUTRAL_RATING_SCORE = 0.5
NEUTRAL_REVIEW_COUNT_SCORE = 0.5

GUARD_CLIP_MIN = 0.0
GUARD_CLIP_MAX = 1.0
RATING_CLIP_MIN = 0.0
RATING_CLIP_MAX = 5.0

POPULARITY_SCORE_DECIMAL_PLACES = 6
