"""MOD-RECO-009 User Context Builder constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-009"
PHASE_NAME = "user_meaning_projected"
SURFACE_ERROR_CODE = "GRS-REC-005"

LAMBDA_CTX_FALLBACK = 0.5
GUARD_CLIP_MIN = 0.0
GUARD_CLIP_MAX = 1.0
LAMBDA_CTX_DECIMAL_PLACES = 4

FREE_TEXT_TRUNCATE_LENGTH = 200
SEMANTIC_QUERY_TOP_K = 5
EMBEDDING_QUERY_TEXT_MAX_LENGTH = 512

EXPECTED_USER_FEATURE_ROW_COUNT = 8
