"""MOD-RECO-020 Final Ranker constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-020"
PHASE_NAME = "ranked"
SURFACE_ERROR_CODE = "GRS-REC-012"

DEFAULT_LAMBDA_MMR = 0.75
DEFAULT_MMR_CANDIDATE_LIMIT = 50
DEFAULT_TOP_K_DEFAULT = 10
DEFAULT_DIVERSITY_METHOD = "mmr"

TOP_K_MIN = 1
TOP_K_MAX = 50

LAMBDA_MMR_MIN = 0.0
LAMBDA_MMR_MAX = 1.0

SCORE_DECIMAL_PLACES = 6
