"""MOD-RECO-018 Risk Scorer constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-018"
PHASE_NAME = "risk_scored"
SURFACE_ERROR_CODE = "GRS-REC-012"

RISK_FORMULA_AVOID_SOCIAL_DATA_QUALITY_WEIGHTED = "avoid_social_data_quality_weighted"
RISK_FORMULA_DEFAULT = RISK_FORMULA_AVOID_SOCIAL_DATA_QUALITY_WEIGHTED

DEFAULT_W_AVOID = 0.50
DEFAULT_W_SOCIAL = 0.30
DEFAULT_W_DATA_QUALITY = 0.20
DEFAULT_SOCIAL_THRESHOLD = 0.60
DEFAULT_ITEM_FEATURE_CONFIDENCE = 0.5

MVP_FEATURE_AXIS_COUNT = 8

GUARD_CLIP_MIN = 0.0
GUARD_CLIP_MAX = 1.0
RISK_PENALTY_DECIMAL_PLACES = 6
