"""MOD-RECO-016 Context Scorer constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-016"
PHASE_NAME = "context_scored"
SURFACE_ERROR_CODE = "GRS-REC-011"

CONTEXT_SCORE_FORMULA_LAMBDA_CTX_WEIGHTED = "lambda_ctx_weighted"
CONTEXT_SCORE_FORMULA_DEFAULT = CONTEXT_SCORE_FORMULA_LAMBDA_CTX_WEIGHTED

LAMBDA_CTX_FALLBACK = 0.5
GUARD_CLIP_MIN = 0.0
GUARD_CLIP_MAX = 1.0
CONTEXT_SCORE_DECIMAL_PLACES = 6
