-- Master seed: concept_feature_rule (sparse MVP; Featureルール定義書 §10.3)
-- semantic_config_version_id = a1111111-1111-4111-8111-111111111102
-- feature_delta = |signed|; polarity = positive|negative (0.00 rows omitted)
-- Human Review #476: sparse seed OK; concept via semantic_concept_id FK
-- expected sparse rows: 112

BEGIN;

WITH rules (
  concept_code,
  feature_code,
  feature_delta,
  polarity
) AS (
  VALUES
    ('formal_refined', 'formality', 0.250::numeric(4, 3), 'positive'),
    ('formal_refined', 'safety', 0.050::numeric(4, 3), 'positive'),
    ('formal_refined', 'brand_appropriateness', 0.200::numeric(4, 3), 'positive'),
    ('formal_refined', 'novelty', 0.050::numeric(4, 3), 'negative'),
    ('formal_refined', 'intimacy', 0.050::numeric(4, 3), 'negative'),
    ('formal_refined', 'symbolic_identity', 0.050::numeric(4, 3), 'positive'),
    ('safe_classic', 'formality', 0.100::numeric(4, 3), 'positive'),
    ('safe_classic', 'safety', 0.300::numeric(4, 3), 'positive'),
    ('safe_classic', 'brand_appropriateness', 0.100::numeric(4, 3), 'positive'),
    ('safe_classic', 'novelty', 0.100::numeric(4, 3), 'negative'),
    ('safe_classic', 'intimacy', 0.050::numeric(4, 3), 'negative'),
    ('prestigious_quality', 'formality', 0.200::numeric(4, 3), 'positive'),
    ('prestigious_quality', 'safety', 0.100::numeric(4, 3), 'positive'),
    ('prestigious_quality', 'brand_appropriateness', 0.300::numeric(4, 3), 'positive'),
    ('prestigious_quality', 'intimacy', 0.050::numeric(4, 3), 'negative'),
    ('prestigious_quality', 'symbolic_identity', 0.100::numeric(4, 3), 'positive'),
    ('prestigious_quality', 'story_richness', 0.100::numeric(4, 3), 'positive'),
    ('practical_useful', 'safety', 0.250::numeric(4, 3), 'positive'),
    ('practical_useful', 'brand_appropriateness', 0.150::numeric(4, 3), 'positive'),
    ('practical_useful', 'emotion', 0.050::numeric(4, 3), 'negative'),
    ('practical_useful', 'novelty', 0.050::numeric(4, 3), 'negative'),
    ('practical_useful', 'story_richness', 0.050::numeric(4, 3), 'negative'),
    ('emotional_warm', 'safety', 0.050::numeric(4, 3), 'positive'),
    ('emotional_warm', 'emotion', 0.300::numeric(4, 3), 'positive'),
    ('emotional_warm', 'intimacy', 0.150::numeric(4, 3), 'positive'),
    ('emotional_warm', 'symbolic_identity', 0.050::numeric(4, 3), 'positive'),
    ('emotional_warm', 'story_richness', 0.050::numeric(4, 3), 'positive'),
    ('special_memorable', 'safety', 0.050::numeric(4, 3), 'negative'),
    ('special_memorable', 'brand_appropriateness', 0.050::numeric(4, 3), 'positive'),
    ('special_memorable', 'emotion', 0.200::numeric(4, 3), 'positive'),
    ('special_memorable', 'novelty', 0.250::numeric(4, 3), 'positive'),
    ('special_memorable', 'intimacy', 0.050::numeric(4, 3), 'positive'),
    ('special_memorable', 'symbolic_identity', 0.100::numeric(4, 3), 'positive'),
    ('special_memorable', 'story_richness', 0.200::numeric(4, 3), 'positive'),
    ('surprising_unique', 'formality', 0.050::numeric(4, 3), 'negative'),
    ('surprising_unique', 'safety', 0.100::numeric(4, 3), 'negative'),
    ('surprising_unique', 'emotion', 0.050::numeric(4, 3), 'positive'),
    ('surprising_unique', 'novelty', 0.300::numeric(4, 3), 'positive'),
    ('surprising_unique', 'intimacy', 0.050::numeric(4, 3), 'positive'),
    ('surprising_unique', 'symbolic_identity', 0.200::numeric(4, 3), 'positive'),
    ('surprising_unique', 'story_richness', 0.100::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'formality', 0.050::numeric(4, 3), 'negative'),
    ('romantic_affectionate', 'safety', 0.050::numeric(4, 3), 'negative'),
    ('romantic_affectionate', 'brand_appropriateness', 0.050::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'emotion', 0.300::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'novelty', 0.100::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'intimacy', 0.300::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'symbolic_identity', 0.200::numeric(4, 3), 'positive'),
    ('romantic_affectionate', 'story_richness', 0.150::numeric(4, 3), 'positive'),
    ('close_personal', 'formality', 0.100::numeric(4, 3), 'negative'),
    ('close_personal', 'brand_appropriateness', 0.050::numeric(4, 3), 'negative'),
    ('close_personal', 'emotion', 0.150::numeric(4, 3), 'positive'),
    ('close_personal', 'novelty', 0.050::numeric(4, 3), 'positive'),
    ('close_personal', 'intimacy', 0.250::numeric(4, 3), 'positive'),
    ('close_personal', 'symbolic_identity', 0.100::numeric(4, 3), 'positive'),
    ('close_personal', 'story_richness', 0.050::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'brand_appropriateness', 0.050::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'emotion', 0.050::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'novelty', 0.050::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'intimacy', 0.100::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'symbolic_identity', 0.300::numeric(4, 3), 'positive'),
    ('symbolic_identity_fit', 'story_richness', 0.200::numeric(4, 3), 'positive'),
    ('story_narrative', 'brand_appropriateness', 0.050::numeric(4, 3), 'positive'),
    ('story_narrative', 'emotion', 0.100::numeric(4, 3), 'positive'),
    ('story_narrative', 'novelty', 0.050::numeric(4, 3), 'positive'),
    ('story_narrative', 'intimacy', 0.050::numeric(4, 3), 'positive'),
    ('story_narrative', 'symbolic_identity', 0.150::numeric(4, 3), 'positive'),
    ('story_narrative', 'story_richness', 0.350::numeric(4, 3), 'positive'),
    ('stylish_aesthetic', 'formality', 0.050::numeric(4, 3), 'negative'),
    ('stylish_aesthetic', 'safety', 0.050::numeric(4, 3), 'negative'),
    ('stylish_aesthetic', 'brand_appropriateness', 0.100::numeric(4, 3), 'positive'),
    ('stylish_aesthetic', 'novelty', 0.250::numeric(4, 3), 'positive'),
    ('stylish_aesthetic', 'intimacy', 0.050::numeric(4, 3), 'positive'),
    ('stylish_aesthetic', 'symbolic_identity', 0.250::numeric(4, 3), 'positive'),
    ('stylish_aesthetic', 'story_richness', 0.050::numeric(4, 3), 'positive'),
    ('cute_soft', 'formality', 0.050::numeric(4, 3), 'negative'),
    ('cute_soft', 'safety', 0.050::numeric(4, 3), 'positive'),
    ('cute_soft', 'brand_appropriateness', 0.050::numeric(4, 3), 'negative'),
    ('cute_soft', 'emotion', 0.200::numeric(4, 3), 'positive'),
    ('cute_soft', 'novelty', 0.150::numeric(4, 3), 'positive'),
    ('cute_soft', 'intimacy', 0.200::numeric(4, 3), 'positive'),
    ('cute_soft', 'symbolic_identity', 0.050::numeric(4, 3), 'positive'),
    ('casual_light', 'formality', 0.200::numeric(4, 3), 'negative'),
    ('casual_light', 'safety', 0.050::numeric(4, 3), 'positive'),
    ('casual_light', 'brand_appropriateness', 0.100::numeric(4, 3), 'negative'),
    ('casual_light', 'emotion', 0.050::numeric(4, 3), 'positive'),
    ('casual_light', 'novelty', 0.050::numeric(4, 3), 'positive'),
    ('casual_light', 'intimacy', 0.100::numeric(4, 3), 'positive'),
    ('not_too_much', 'formality', 0.100::numeric(4, 3), 'negative'),
    ('not_too_much', 'safety', 0.100::numeric(4, 3), 'positive'),
    ('not_too_much', 'brand_appropriateness', 0.150::numeric(4, 3), 'negative'),
    ('not_too_much', 'emotion', 0.200::numeric(4, 3), 'negative'),
    ('not_too_much', 'novelty', 0.050::numeric(4, 3), 'negative'),
    ('not_too_much', 'intimacy', 0.250::numeric(4, 3), 'negative'),
    ('not_too_much', 'symbolic_identity', 0.100::numeric(4, 3), 'negative'),
    ('not_too_much', 'story_richness', 0.050::numeric(4, 3), 'negative'),
    ('not_too_safe', 'safety', 0.250::numeric(4, 3), 'negative'),
    ('not_too_safe', 'emotion', 0.050::numeric(4, 3), 'positive'),
    ('not_too_safe', 'novelty', 0.200::numeric(4, 3), 'positive'),
    ('not_too_safe', 'symbolic_identity', 0.050::numeric(4, 3), 'positive'),
    ('not_too_safe', 'story_richness', 0.050::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'formality', 0.100::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'brand_appropriateness', 0.250::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'emotion', 0.150::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'novelty', 0.200::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'symbolic_identity', 0.100::numeric(4, 3), 'positive'),
    ('luxurious_rich', 'story_richness', 0.100::numeric(4, 3), 'positive'),
    ('cheerful_positive', 'formality', 0.050::numeric(4, 3), 'negative'),
    ('cheerful_positive', 'emotion', 0.250::numeric(4, 3), 'positive'),
    ('cheerful_positive', 'novelty', 0.150::numeric(4, 3), 'positive'),
    ('cheerful_positive', 'intimacy', 0.050::numeric(4, 3), 'positive'),
    ('cheerful_positive', 'symbolic_identity', 0.050::numeric(4, 3), 'positive')
)
INSERT INTO concept_feature_rule (
  semantic_config_version_id,
  semantic_concept_id,
  feature_code,
  feature_delta,
  polarity,
  is_active
)
SELECT
  'a1111111-1111-4111-8111-111111111102'::uuid,
  sc.semantic_concept_id,
  rules.feature_code,
  rules.feature_delta,
  rules.polarity,
  true
FROM rules
JOIN semantic_concept sc
  ON sc.semantic_config_version_id = 'a1111111-1111-4111-8111-111111111102'::uuid
 AND sc.concept_code = rules.concept_code
ON CONFLICT (semantic_config_version_id, semantic_concept_id, feature_code)
DO UPDATE SET
  feature_delta = EXCLUDED.feature_delta,
  polarity = EXCLUDED.polarity,
  is_active = EXCLUDED.is_active;

COMMIT;

