"""MOD-RECO-019 Final Score Calculator constants."""

from __future__ import annotations

MODULE_ID = "MOD-RECO-019"
PHASE_NAME = "final_score_calculated"
SURFACE_ERROR_CODE = "GRS-REC-012"

FINAL_SCORE_FORMULA_LINEAR_WEIGHTED_V1 = "linear_weighted_v1"
FINAL_SCORE_FORMULA_DEFAULT = FINAL_SCORE_FORMULA_LINEAR_WEIGHTED_V1

DEFAULT_W_CONTEXT = 0.70
DEFAULT_W_POPULARITY = 0.20
DEFAULT_W_RISK = 0.10
DEFAULT_POPULARITY_SCORE_MISSING = 0.5
DEFAULT_RISK_PENALTY_MISSING = 0.0
DEFAULT_DIVERSITY_PENALTY = 0.0

WEIGHT_SUM_TOLERANCE = 0.001

GUARD_CLIP_MIN = 0.0
GUARD_CLIP_MAX = 1.0
FINAL_SCORE_DECIMAL_PLACES = 6
